image: Ubuntu1804

stack: node 16

branches:
  only:
    - main

cache: node_modules  # кеширование

install:
  - npm install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - npm run build

test_script:
  - npm run lint && npm test
